services:
  backend:
    build:
      context: ./
    ports:
      - "8000:8000"
    environment:
      - port=8000
      - DATABASE_URL=postgres://postgres:password@db:5432/db
    depends_on:
      - db
    volumes:
      - ./:/app
      - /app/node_module 
  
  db:
    image: postgres:16
    container_name: postgres_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    restart: always
    # volumes:
    #   - db_data:/var/lib/postgresql/data